apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-redis
  template:
    metadata:
      labels:
        app: inventory-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
